networks:
  swaga-network:
    driver: bridge
    external: true
    name: swaga-network

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "./wait-for-it.sh gateway-service:5000 -- npm run dev"]
    image: ghcr.io/swagateam/frontend:1.0.3 
    ports:
      - 5173:5173
    networks:
      - swaga-network
    env_file:
      - .env

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    image: ghcr.io/swagateam/nginx:1.0.3  
    ports:
      - "443:443" 
    command: ["sh", "-c", "./wait-for-it.sh client:5173 -- nginx -g 'daemon off;'"]
    volumes:
      - /nginx/ssl:/etc/nginx/ssl 
      - /etc/letsencrypt:/etc/letsencrypt 
    depends_on:
      - client
    networks:
      - swaga-network