networks:
  swaga-network:
    driver: bridge
    name: swaga-network

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - 5173:5173
    networks:
      swaga-network: